---
AWSTemplateFormatVersion: 2010-09-09
Resources:
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${AWS::StackName}-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowLambdaService"
            Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: "lambda/dist/index.zip"
      Handler: "handler"
      Runtime: "nodejs24.x"
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: "csv-to-json"
      Description: "Converts a csv object to json"
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::*"
      SourceAccount: !Ref AWS::AccountId
  CsvToJsonBucket:
    Type: "AWS::S3::Bucket"
    Metadata:
      guard:
        SuppressedRules:
          - S3_BUCKET_VERSIONING_ENABLED
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      VersioningConfiguration:
        Status: "Suspended"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put # Triggers only on PUT uploads
            Function: !GetAtt LambdaFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: /incoming
  PolicyForBucketAccess:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Sub "${AWS::StackName}-lamda-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "S3Access"
            Effect: "Allow"
            Action:
              - "s3:ListBucket"
              - "s3:GetObject"
              - "s3:PutObject"
            Resource: !Sub "${CsvToJsonBucket.Arn}/*"
      Roles:
        - !Ref LambdaExecutionRole
